### ISSUE TITLE
Question Training fonts max_iterations 

### ISSUE THREAD

**Issue by eliyaz-kl** [UYousafzai/easy_train_tesseract#3]
Hi, 
I hope this repo will be helpful for people like me, looking for training.

**I have the following doubts:**
1. how much dataset set (.gt.txt files) do i need for training, for both if i need to train from scratch or fine tune pre trained model.
2. apx how many max_iterations i need to set.
3. how to decide the max_iterations is there any ratio of datasets and iteration.

my use case is on Arabic document, the pre retrained ara.traineddata are good but not perfect. so i wish to fine tune ara.traineddata, if the results are not satisfying then have train my own custom data.

**please suggest me for the following:**
1. for my use case in Arabic text, problem is in one character which is always predicting wrong.
so do i need to add the font (traditional arabic font) and use your fonts repo to train? 
if yes how many gt.txt files i need and how many characters needs to be there in each file? and any apx iterations if you know?
2. for number, the prediction is totally wrong on Arabic numbers, so do i need to start from scratch or need to fine tune? if any then how to prepare datasets for the same.

**Comment by UYousafzai** [comment]
Hi Eliyaz, hope you're doing good, sorry for the late reply, I have been super busy with work but I'll try my best to answer your questions:

#### Answers:
1. The Readme has the step3: changing parameters point 1 which states that 250 pages was a good number for me at the time of writing this repository, also with pages it takes a huge amount of time in training so choose a suitable number that both would be sufficient yet less time consuming, if you're data is completely unique only then would I suggest a number greater than 500 otherwise try staying around that number.

2.  max iterations that I used was 2000, at that number the model doesn't over fit alot but it does a little which I like because I had an objective of having a bias towards a particular font, if you don't want any over fitting try going for 1500.

3. unfortunately I don't know a well defined set of rules on choosing this number, I have always seen this as a more of an intuition approach where if I find a font complex or different enough, I'll choose a higher number and if I find it similar or has a remote resemblance to well known fonts I choose a lower number.

#### Suggestions:
shoot me a mail at umaryousafzai9@gmail.com, we encountered a similar problem but it needs a bit of questioning back and forth in order to decide what strategy could be used to find a solution to your problem and lets have that over at the email or maybe a call.

Note: I am going to mark this issue resolved but feel free to create a new one if you have any other or mail me in case of the suggestions and finding the solution to your problems.
